### ISSUE TITLE
Using breaks with other components

### ISSUE THREAD

**Issue by druellan** [nygardk/react-break#2]
Hi! Love this component, but I'm having problems using it in conjunction with other components, likes this:

```
<OnTablet>
<Panel {...props} />
</OnTablet>
```

or

```
<OnTablet>
(...)
</OnTablet>
<Panel {...props} />
```

On both cases, "Panel" is not working as expected, seems that "props" is affected on same way, because the component behaves erratically or just plain fails to mount.

This happens usually when using 'atLeast' as bp method.
I'm new to React, so, the feedback I can provide is somehow limited, but let me know if I can do some tests with anything.

Thanks!

@"react": "^15.3.1",

**Comment by nygardk** [comment]
Hi! Based on what you describe, I think the problem is not caused react-break. However, it is impossible to say for sure. I can try to help if you provide a more complete example of what you are doing in your code.

**Comment by druellan** [comment]
Hi @nygardk  Thanks for the reply. So sorry about the lack of information, was late at night and I was tired and a bit frustrated. I'm going to try and amend that right now.

The situation is weird, because I have two instances on where the components start behaving erratically ONLY when react-break is present on the template, and seems related to the use of 'atLeast' but I'm not 100% sure.

This is a somehow complex app, so, as you say, could be other things, but I can confirm that the problem is present only when using react-break. The implementation looks like this:

I have a wrapper method on the main app.js
```
import { layoutGenerator } from 'react-break';

const layout = layoutGenerator({
  mobile: 0,
  tablet: 768,
  desktop: 1025
});

this.checkLayout = this.checkLayout.bind(this);
checkLayout(op, bp) {
  return layout(op, bp);
}
```

I reveal everything to the component:
```
<PanelContainer
{...this}
{ ...state }
showAll={ this.showAll }
updateNewsFeed={ this.updateNewsFeed }
updateAppState={ this.updateAppState }
updateChannels={ this.updateChannels} 
checkLayout={ this.checkLayout } />
```

In the component container, I have this:
```
export const PanelContainer = (props) =>  {
    const OnTablet = props.checkLayout('atLeast', 'tablet');

    return (
      <OnTablet>
        <Panel {...props} />
      </OnTablet>
    );
}
```
As far as I can see, the template hits the breakpoint ok (the element is displayed on "tablet" and above), the state of the app is also refreshed, I can see variables changing when I interact with "Panel", but there is no refresh on the DOM for that particular component. The rest of the app is behaving OK.
No errors on the console.

-- o --

I'm using a similar implementation on another component:
```
const OnTablet = checkLayout('atLeast', 'tablet');
    return (
      <div className={`Feed ${mapAnimation}`}>
        <OnTablet>
        <Chart feedprops={this.props} />
        </OnTablet>
        <Masonry
          className={'ui-grid'}
          elementType={'ul'}
          options={masonryOptions}
          disableImagesLoaded={false}
          updateOnEachImageLoad={false}
        >
(...)
```
In this case, no only "Chart" is not behaving correctly (again, seems that the DOM is not refreshing based on the state of the app), but also "Masonry" fails to be displayed: the container is totally empty.
If I remove the OnTablet tag, everything works as expected.

-- o --

And, I also have this implementation. I can confirm that so far this SEEMS TO WORK:
```
export const NavigationContainer = (props) => {
  const OnMobile = props.checkLayout('is', 'mobile');
  return (
    <OnMobile>
    <div className="mobile-navigation">
        <Navigation {...props} />
    </div>
    </OnMobile>
  );
}
```
Here I'm using "IS" as BP method. This components is work OK.

Thanks again for any help!

**Comment by druellan** [comment]
Confirmed seems not related to the use of "atLeast" or the presence of a wrapper div.

**Comment by druellan** [comment]
Now using 1.0.1, same problem. No changes :(

**Comment by nygardk** [comment]
Are you using a linter and a module bundler? Are you certain that you have no invalid references ? No run-time errors in browser console?

`this.checkLayout` seems a bit odd way to propagate the layout through components. I would suggest to create the layout components in a separate module and import them from there. Also, you are creating e.g. `OnTablet` component in PanelContainer _every time_ the app is re-rendered. You should move the component declarations out from the render functions.

A little but noteworthy thing is that you are calling "this.checkLayout(...)". It is semantically incorrect, since the `layout` you created with `layoutGenerator` is not "checking" anything when you call the `is`, `isAtLeast` and `isAtMost` methods. Instead, it generates a component. So in fact, the `layoutGenerator` is a factory function that returns another "component generator" factory function, which is configured for the layout. This is just for you to know.

Also, be aware of the breaking changes from `v0.4.0` to `v1.0.1` (see release notes).

**Comment by druellan** [comment]
Thanks @nygardk.

> Are you using a linter and a module bundler? Are you certain that you have no invalid references ? No run-time errors in browser console?
Yes, because your component is actually working fine, the problem is that it changes the way other components react when is present on the template.

I've reimplemented everything based on 1.0.1, and now I'm calling the component directly inside my container. I have identical results.

What now I can theorize is that React seems to be repainting the child element on every interaction and is resetting some states. For example, I have this:
```
      <OnAtLeastTablet>
        <Chart {...props} />
      </OnAtLeastTablet>
```
The Chart component is an interactive Map. If I try to interact with the Map, or I resize the browser window, the map is forced to reinitialize, like the DOM being destroyed and recreated every time. If I remove your component, everything works fine. 

This is the full code:

I generate the component function on the app.js:
```
    this.checkLayout = layoutGenerator({
      mobile: 0,
      tablet: 768,
      desktop: 1025
    });
```
I pass that to my own component:
```
          <MainContainer
            { ...state }
            showAll={ this.showAll }
            updateNewsFeed={ this.updateNewsFeed }
            updateAppState={ this.updateAppState }
            updateChannels={ this.updateChannels }
            checkLayout={ this.checkLayout } />
```
On my component I check the layout:
```
export const PanelContainer = (props) =>  {

    const OnAtLeastTablet = props.checkLayout.isAtLeast('tablet');

    return (
      <OnAtLeastTablet>
        <Panel {...props} />
      </OnAtLeastTablet>
    );
}
```

**Comment by druellan** [comment]
I'm using now this approach:
```
        <Break
          breakpoints={UIBreakpoints}
          query={{ method: 'isAtLeast', breakpoint: 'tablet' }}>
          <Chart feedprops={this.props} />
        </Break>
```
And seems to work better, at least I have no unwanted refreshes in the DOM.

**Comment by druellan** [comment]
Confirmed that seems to work allright!
