### ISSUE TITLE
Warning forceUpdate

### ISSUE THREAD

**Issue by nckblu** [nygardk/react-break#5]
I'm finding that when changing breakpoints by resizing I get a forceUpdate error:

`warning.js:36 Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the Break component.`

**Comment by nckblu** [comment]
This was my fault, I realised that by declaring the layout variables within render it caused this issue, if anyone else finds this, that's probably why.

**Comment by nckblu** [comment]
I'm re-opening this because I'm finding this warning creeping back intermittently on resize, has anyone found this?

**Comment by nygardk** [comment]
I have encountered the warning (only) when react-hot-loader reloads the app on a file change. Can you confirm if this is the case for you, too?

**Comment by nckblu** [comment]
Yes I think that's it! Thanks
