### ISSUE TITLE
Strange issue with test runner

### ISSUE THREAD

**Issue by nckblu** [nygardk/react-break#6]
I'm finding when I'm running a require.context to get all of my files and react-break gets required, it fails all tests and returns:

```
TypeError: undefined is not a constructor (evaluating '(0, _keys2.default)(breakpoints).includes(breakpoint)')
  at webpack:///~/react-break/lib/react-break.js:145:0 <- tests/test-bundler.js:244931
```

Apologies if this is not an issue of react-break

**Comment by nygardk** [comment]
I'm a bit unsure what you mean by requiring all your files? You are attempting to scan for all tests and run them? You should run anything directly from node_modules in your tests.

**Comment by nckblu** [comment]
In order to generate coverage everything in 'src' is requred:

// require all `src/**/*.js` except for `main.js` (for isparta coverage reporting)

```
if (__COVERAGE__) {
  const componentsContext = require.context("../src/", true, /^((?!main|reducers).)*\.js$/);
  componentsContext.keys().forEach(componentsContext);
}
```

**Comment by nckblu** [comment]
I'm going to close this as after a bit of digging it is a phantomJS issue, when defining components like so, it really doesn't like it:
`OnMobile = layout.is("mobile");`

**Comment by nygardk** [comment]
My educated guess is that providing a polyfill (e.g. babel-polyfill) could have some effect on the issue.

**Comment by nckblu** [comment]
Thank you, you were absolutely right, I just added the babel-polyfill to my test bundling script and it worked fine.
